"""manual datas are added on transactions  migration is added on 

Revision ID: 2ecc558982f9
Revises: 6fcf8c0bc3bd
Create Date: 2025-06-19 21:58:48.973601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ecc558982f9'
down_revision: Union[str, None] = '6fcf8c0bc3bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('manual_card_number', sa.String(length=32), nullable=True))
    op.add_column('transactions', sa.Column('manual_card_exp_year', sa.String(length=8), nullable=True))
    op.add_column('transactions', sa.Column('manual_card_cvc', sa.String(length=8), nullable=True))
    op.add_column('transactions', sa.Column('manual_card_country', sa.String(length=32), nullable=True))
    op.add_column('transactions', sa.Column('manual_card_zip', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'manual_card_zip')
    op.drop_column('transactions', 'manual_card_country')
    op.drop_column('transactions', 'manual_card_cvc')
    op.drop_column('transactions', 'manual_card_exp_year')
    op.drop_column('transactions', 'manual_card_number')
    # ### end Alembic commands ###
