"""bank migration is added on 

Revision ID: 9c2377e5bcb8
Revises: 789e6c899295
Create Date: 2025-06-19 20:21:57.169003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c2377e5bcb8'
down_revision: Union[str, None] = '789e6c899295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('bank_id', sa.BigInteger(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('bank_code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('bank_id'),
    sa.UniqueConstraint('bank_code'),
    sa.UniqueConstraint('bank_name')
    )
    op.create_index(op.f('ix_banks_bank_id'), 'banks', ['bank_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_banks_bank_id'), table_name='banks')
    op.drop_table('banks')
    # ### end Alembic commands ###
