"""Add transfer_fee to transactions

Revision ID: e7a6be3225e1
Revises: ea7b338d6789
Create Date: 2025-06-19 00:01:28.452514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7a6be3225e1'
down_revision: Union[str, None] = 'ea7b338d6789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transfer_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'transfer_fee')
    # ### end Alembic commands ###
