"""Initial migration

Revision ID: ea7b338d6789
Revises: 
Create Date: 2025-06-09 23:19:26.065332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea7b338d6789'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_us',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_us_id'), 'contact_us', ['id'], unique=False)
    op.create_table('exchange_rates',
    sa.Column('exchange_rate_id', sa.BigInteger(), nullable=False),
    sa.Column('from_currency', sa.String(length=10), nullable=False),
    sa.Column('to_currency', sa.String(length=10), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('buying_rate', sa.Float(), nullable=True),
    sa.Column('selling_rate', sa.Float(), nullable=True),
    sa.Column('rate', sa.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('available_balance_from', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('available_balance_to', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('exchange_rate_id')
    )
    op.create_index(op.f('ix_exchange_rates_exchange_rate_id'), 'exchange_rates', ['exchange_rate_id'], unique=False)
    op.create_table('transaction_fees',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('stripe_fee', sa.Float(), nullable=True),
    sa.Column('service_fee', sa.Float(), nullable=True),
    sa.Column('margin', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_fees_id'), 'transaction_fees', ['id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', 'finance_officer', 'support', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('suspended_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('suspension_reason', sa.Text(), nullable=True),
    sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('kyc_status', sa.Enum('pending', 'approved', 'rejected', name='kycstatus'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('otp_code', sa.String(length=6), nullable=True),
    sa.Column('otp_expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('user_weekly_limit', sa.BigInteger(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('admin_roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_roles_id'), 'admin_roles', ['id'], unique=False)
    op.create_table('kyc_documents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('street_name', sa.String(length=100), nullable=True),
    sa.Column('house_no', sa.String(length=50), nullable=True),
    sa.Column('additional_info', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='genderenum'), nullable=True),
    sa.Column('id_type', sa.Enum('passport', 'national_id', 'driver_license', name='idtypeenum'), nullable=True),
    sa.Column('front_image', sa.String(length=255), nullable=False),
    sa.Column('back_image', sa.String(length=255), nullable=True),
    sa.Column('selfie_image', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='kycstatus'), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_documents_id'), 'kyc_documents', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'sms', 'push', name='channeltype'), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('doc_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=False)
    op.create_index('ix_user_is_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('payment_cards',
    sa.Column('payment_card_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('card_type', sa.Enum('VISA', 'MASTER_CARD', 'AMERICAN_EXPRESS', 'DISCOVER', 'PAYONEER', 'OTHER', name='cardtype'), nullable=False),
    sa.Column('stripe_payment_method_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('last4', sa.String(length=4), nullable=True),
    sa.Column('exp_month', sa.Integer(), nullable=True),
    sa.Column('exp_year', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_card_id')
    )
    op.create_index(op.f('ix_payment_cards_payment_card_id'), 'payment_cards', ['payment_card_id'], unique=False)
    op.create_table('recipients',
    sa.Column('recipient_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('account_type', sa.Enum('bank_account', 'telebirr', name='accounttype'), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('telebirr_number', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.String(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipient_id')
    )
    op.create_index(op.f('ix_recipients_recipient_id'), 'recipients', ['recipient_id'], unique=False)
    op.create_table('admin_activities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('activity', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_activities_id'), 'admin_activities', ['id'], unique=False)
    op.create_table('admin_permissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('permission', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_permissions_id'), 'admin_permissions', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_card_id', sa.BigInteger(), nullable=True),
    sa.Column('stripe_charge_id', sa.String(length=255), nullable=True),
    sa.Column('transaction_reference', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'active', name='transactionstatus'), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('account_type', sa.Enum('bank_account', 'telebirr', name='accounttype'), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('telebirr_number', sa.String(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['payment_card_id'], ['payment_cards.payment_card_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=False)
    op.create_table('manual_deposits',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('deposit_proof_image', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_deposits_id'), 'manual_deposits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manual_deposits_id'), table_name='manual_deposits')
    op.drop_table('manual_deposits')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_admin_permissions_id'), table_name='admin_permissions')
    op.drop_table('admin_permissions')
    op.drop_index(op.f('ix_admin_activities_id'), table_name='admin_activities')
    op.drop_table('admin_activities')
    op.drop_index(op.f('ix_recipients_recipient_id'), table_name='recipients')
    op.drop_table('recipients')
    op.drop_index(op.f('ix_payment_cards_payment_card_id'), table_name='payment_cards')
    op.drop_table('payment_cards')
    op.drop_index('ix_user_is_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_kyc_documents_id'), table_name='kyc_documents')
    op.drop_table('kyc_documents')
    op.drop_index(op.f('ix_admin_roles_id'), table_name='admin_roles')
    op.drop_table('admin_roles')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transaction_fees_id'), table_name='transaction_fees')
    op.drop_table('transaction_fees')
    op.drop_index(op.f('ix_exchange_rates_exchange_rate_id'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    op.drop_index(op.f('ix_contact_us_id'), table_name='contact_us')
    op.drop_table('contact_us')
    # ### end Alembic commands ###
